server:
  port: 8020
spring:
  application:
    name: storage-service
  datasource:
    url: jdbc:mysql://localhost:3306/storagedb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"


management:
  endpoints:
    web:
      exposure:
        include: "*"